// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
	export interface GlobalComponents {
		MdEn: typeof import('./components/md/en.vue')['default'];
		MdKo: typeof import('./components/md/ko.vue')['default'];
		MdWrapper: typeof import('./components/md/wrapper.vue')['default'];
		UiBlock: typeof import('./components/ui/block.vue')['default'];
	}
}

export {};
